// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(MFDllContext))]
    [Migration("20220215154229_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Connectors.Models.Instruments.Future", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstumentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketRule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinTick")
                        .HasColumnType("TEXT");

                    b.Property<int>("Multiplier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Future");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FutureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstumentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketRule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinTick")
                        .HasColumnType("TEXT");

                    b.Property<int>("Multiplier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptionType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Strike")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FutureId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("DataLayer.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MainStrategies");
                });

            modelBuilder.Entity("DataLayer.Models.LongStraddle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongStraddleLogic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("LongStraddles");
                });

            modelBuilder.Entity("DataLayer.Models.Strategies.DbOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgFilledPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LmtPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OptionStrategyId");

                    b.ToTable("DbOrders");
                });

            modelBuilder.Entity("DataLayer.Models.Strategies.OptionStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongStraddleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyLogic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LongStraddleId");

                    b.HasIndex("OptionId");

                    b.ToTable("OptionStrategies");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Option", b =>
                {
                    b.HasOne("Connectors.Models.Instruments.Future", "Future")
                        .WithMany("Options")
                        .HasForeignKey("FutureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Future");
                });

            modelBuilder.Entity("DataLayer.Models.LongStraddle", b =>
                {
                    b.HasOne("DataLayer.Models.Container", "Container")
                        .WithMany("LongStraddles")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("DataLayer.Models.Strategies.DbOrder", b =>
                {
                    b.HasOne("DataLayer.Models.Strategies.OptionStrategy", "OptionStrategy")
                        .WithMany("StrategyOrders")
                        .HasForeignKey("OptionStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionStrategy");
                });

            modelBuilder.Entity("DataLayer.Models.Strategies.OptionStrategy", b =>
                {
                    b.HasOne("DataLayer.Models.LongStraddle", "LongStraddle")
                        .WithMany("OptionStrategies")
                        .HasForeignKey("LongStraddleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectors.Models.Instruments.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LongStraddle");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Future", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DataLayer.Models.Container", b =>
                {
                    b.Navigation("LongStraddles");
                });

            modelBuilder.Entity("DataLayer.Models.LongStraddle", b =>
                {
                    b.Navigation("OptionStrategies");
                });

            modelBuilder.Entity("DataLayer.Models.Strategies.OptionStrategy", b =>
                {
                    b.Navigation("StrategyOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
