// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(MFDllContext))]
    [Migration("20220217095506_for now only instruments in DB")]
    partial class fornowonlyinstrumentsinDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Connectors.Models.Instruments.Future", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstumentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketRule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinTick")
                        .HasColumnType("TEXT");

                    b.Property<int>("Multiplier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Future");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Future");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FutureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstumentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketRule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinTick")
                        .HasColumnType("TEXT");

                    b.Property<int>("Multiplier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptionType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Strike")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FutureId");

                    b.ToTable("Option");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Option");
                });

            modelBuilder.Entity("DataLayer.Models.Instruments.DbFuture", b =>
                {
                    b.HasBaseType("Connectors.Models.Instruments.Future");

                    b.HasDiscriminator().HasValue("DbFuture");
                });

            modelBuilder.Entity("DataLayer.Models.Instruments.DbOption", b =>
                {
                    b.HasBaseType("Connectors.Models.Instruments.Option");

                    b.HasDiscriminator().HasValue("DbOption");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Option", b =>
                {
                    b.HasOne("Connectors.Models.Instruments.Future", "Future")
                        .WithMany("Options")
                        .HasForeignKey("FutureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Future");
                });

            modelBuilder.Entity("Connectors.Models.Instruments.Future", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
